# Usage
#   Start:          docker compose up
#   Stop:           docker compose down
#   Destroy:        docker compose down -v --remove-orphans
#   Start services: docker compose up [service_name(s) tab separated] -d
#         Eg   :  docker compose up templrjs

version: '3.7'

networks:
  traefik-public:
    external: true

services:
  templrjs:
    image: senthilsweb/templrjs:latest
    container_name: templrjs
    networks:
      - traefik-public
    restart: unless-stopped
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./public:/app/.output/public
    environment:
      - NUXT_PUBLIC_API_BASE_URL=https://duckdb-data-api.vercel.app
      - NUXT_SESSION_PASSWORD=55785e3af0e33cb97aceafb9dbe6aa72n
      - NUXT_PUBLIC_DUCKDB_DATA_API_BASE_PATH=https://duckdb-data-api.vercel.app
      - NUXT_PUBLIC_CLOUDINARY_BASE_URL="https://res.cloudinary.com/nathansweb"
      - NUXT_PUBLIC_CLOUDINARY_PUBLIC_ID="v1713094928/senthilsweb.com/blog-pink-bg_cegrcz.png"
      - NUXT_PUBLIC_TEMPLRJS_CONFIG_ROOT_PATH=https://www.senthilsweb.com/configs
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.templrjs.tls=true'
      - 'traefik.http.routers.templrjs.rule=Host(`templrjs.senthilsweb.com`)'
      - 'traefik.http.routers.templrjs.entrypoints=websecure'
      - 'traefik.http.routers.templrjs.tls.certresolver=myresolver'
