name: TemplrJS - PostgreSQL DB backup

on:
  workflow_dispatch:
    branches:
    - main
env:
  DB_CONN_URI: ${{ secrets.POSTGRES_CONNECTION_STRING }}
#
jobs:
  docker:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade PostgreSQL on Ubuntu
        run: |
         sudo apt-get install postgresql-client

      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: ${{ env.DB_CONN_URI }}
          path: "backups/backup.sql" 
          options: "-O"   

