name: TemplrJS - build release candidate

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  create-deployment-artefacts:
    name: Create Deployment Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.19.1
    env:
      working-directory: .
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - name: Create .env file
        run: cp release.env .env
      - run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz  ./.output ./.env ./run.sh ./.data
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v3
        with:
          name: templrjs_${{ steps.vars.outputs.date }}_${{ steps.vars.outputs.sha_short }}.tar.gz
          path: ${{ github.sha }}.tar.gz
