name: TemplrJS - build release candidate

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  create-deployment-artefacts:
    name: Create Deployment Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.9.0
    env:
      working-directory: .
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - name: Create .env file
        run: cp release.env .env
      - run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz  ./.output ./.env ./run.sh ./.data
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v3
        with:
          name: templrjs_$(date +'%Y-%m-%d').tar.gz
          path: ${{ github.sha }}.tar.gz
